"""Phase 2, step 1: build the reproducible split manifest  data/splits.csv  and a leakage report.

Run:  python scripts/make_splits.py            (uses seed 42 from configs/default.yaml)

Output columns: path, filename, label, label_id, defect_type, group, split ('test'|'trainval'), fold (0-4, -1 for test)
"""
import argparse
import math
import sys
from pathlib import Path

import numpy as np
import pandas as pd
import yaml

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from src.dupes import GROUP_THRESHOLD, duplicate_groups, thumbnail_matrix  # noqa: E402
from src.splits import assign_splits  # noqa: E402


def wilson_halfwidth(p: float, n: int, z: float = 1.96) -> float:
    """Half-width of the 95% Wilson confidence interval for a proportion p measured on n samples."""
    if n == 0:
        return float("nan")
    centre_adj = z * math.sqrt(p * (1 - p) / n + z * z / (4 * n * n)) / (1 + z * z / n)
    return centre_adj


def twin_leak_count(T, a_idx, b_idx, thr=GROUP_THRESHOLD):
    """How many images in set A have a near-identical twin (corr > thr) somewhere in set B?"""
    C = T[a_idx] @ T[b_idx].T
    return int((C.max(1) > thr).sum()), float(C.max())


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--data", default="data/raw")
    ap.add_argument("--config", default="configs/default.yaml")
    ap.add_argument("--out", default="data/splits.csv")
    ap.add_argument("--report", default="docs/split_report.md")
    a = ap.parse_args()
    seed = yaml.safe_load(open(a.config))["seed"]

    # ---- 1. list images (class = folder, defect type = filename prefix)
    rows = []
    for cls in ["normal", "defective"]:
        for p in sorted((Path(a.data) / cls).glob("*")):
            if p.suffix.lower() in {".jpg", ".jpeg", ".png", ".bmp"}:
                dtype = p.name.split("__")[0] if "__" in p.name else cls  # fall back to class if no prefix
                rows.append({"path": p.as_posix(), "filename": p.name, "label": cls,
                             "label_id": int(cls == "defective"), "defect_type": dtype})
    df = pd.DataFrame(rows)

    # ---- 2. duplicate groups, then split BY GROUP
    T = thumbnail_matrix(df.path)
    df["group"] = duplicate_groups(T)
    df["split"], df["fold"] = assign_splits(df.defect_type, df.group, seed=seed)
    df.to_csv(a.out, index=False)

    # ---- 3. hard checks (the script fails loudly if any is violated)
    g_split = df.groupby("group").split.nunique()
    assert (g_split == 1).all(), "a duplicate group appears in both test and trainval!"
    tv = df[df.split == "trainval"]
    assert (tv.groupby("group").fold.nunique() == 1).all(), "a duplicate group spans two CV folds!"
    assert set(df[df.split == "test"].defect_type) == set(df.defect_type), "test misses a defect type"

    # ---- 4. leakage evidence: ours vs a NAIVE random image-level split of the same size
    test_idx = np.where(df.split == "test")[0]
    tv_idx = np.where(df.split == "trainval")[0]
    ours, ours_max = twin_leak_count(T, test_idx, tv_idx)
    rng = np.random.default_rng(seed)
    perm = rng.permutation(len(df))
    naive_test, naive_tv = perm[: len(test_idx)], perm[len(test_idx):]
    naive, naive_max = twin_leak_count(T, naive_test, naive_tv)

    # ---- 5. report
    def table(sub, by):
        return pd.crosstab(sub[by], sub.defect_type, margins=True).to_markdown()

    n_test_def = int(((df.split == "test") & (df.label == "defective")).sum())
    ci_rows = "\n".join(
        f"| {r:.2f} | +/- {wilson_halfwidth(r, n_test_def) * 100:.1f} pp |" for r in (0.85, 0.90, 0.95)
    )
    per_split = df.assign(role=np.where(df.split == "test", "test", "fold " + df.fold.astype(str))) \
        .groupby("role").agg(images=("path", "size"), tiles=("group", "nunique"),
                             defective=("label_id", "sum")).assign(
        defective_pct=lambda d: (100 * d.defective / d.images).round(1))
    rep = f"""# Split report (auto-generated by scripts/make_splits.py, seed {seed})

Unit of splitting = duplicate group (correlation > {GROUP_THRESHOLD}); stratified by defect type.

## Sizes
{per_split.to_markdown()}

Test = {len(test_idx)} images ({100 * len(test_idx) / len(df):.1f}%). With 5 CV folds, train/val/test per run = about
{100 * (len(tv_idx) * 4 / 5) / len(df):.0f}% / {100 * (len(tv_idx) / 5) / len(df):.0f}% / {100 * len(test_idx) / len(df):.1f}%.

## Defect types per role
{table(df.assign(role=np.where(df.split == 'test', 'test', 'fold ' + df.fold.astype(str))), 'role')}

## Leakage check (images that have a near-identical twin, corr > {GROUP_THRESHOLD}, on the other side of the test boundary)
| split method | test images with a twin in train/val | highest test<->train correlation |
|---|---|---|
| **this project (group-aware)** | **{ours}** of {len(test_idx)} | {ours_max:.3f} |
| naive random image split (same sizes) | {naive} of {len(test_idx)} ({100 * naive / len(test_idx):.0f}%) | {naive_max:.3f} |

## How certain can the test numbers be? (95% Wilson interval, test has {n_test_def} defective images)
| true recall | interval half-width |
|---|---|
{ci_rows}

These intervals are OPTIMISTIC: they treat every image as independent, but crops of one tile are correlated,
so the effective sample is closer to the number of tiles. Phase 4 will bootstrap by group instead.

A single test set this small gives wide intervals: any metric must be reported with its interval, and
differences of a few points between models are NOT significant.
"""
    Path(a.report).write_text(rep)
    print(rep)


if __name__ == "__main__":
    main()
